//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsMinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrescriptionTable()
        {
            this.ReminderTables = new HashSet<ReminderTable>();
        }
    
        public int PrescriptionID { get; set; }
        public string PrescriptionName { get; set; }
        public int PetID { get; set; }
        public string PetName { get; set; }
        public int MedicineID { get; set; }
        public string MedicineName { get; set; }
        public decimal DosagePerDay { get; set; }
        public int UnitID { get; set; }
        public string Unit { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string VeterinaryName { get; set; }
        public string VeterinaryPhone { get; set; }
        public string Notes { get; set; }
    
        public virtual MedicineTable MedicineTable { get; set; }
        public virtual PetTable PetTable { get; set; }
        public virtual UnitTable UnitTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReminderTable> ReminderTables { get; set; }
    }
}
