//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsMinder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PsMinderEntities : DbContext
    {
        public PsMinderEntities()
            : base("name=PsMinderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CredentialTable> CredentialTables { get; set; }
        public virtual DbSet<MedicineTable> MedicineTables { get; set; }
        public virtual DbSet<PetTable> PetTables { get; set; }
        public virtual DbSet<PrescriptionTable> PrescriptionTables { get; set; }
        public virtual DbSet<ReminderTable> ReminderTables { get; set; }
        public virtual DbSet<UnitTable> UnitTables { get; set; }
    }
}
