//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsMinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReminderTable
    {
        public int ReminderID { get; set; }
        public int PrescriptionID { get; set; }
        public string PrescriptionName { get; set; }
        public int PetID { get; set; }
        public string PetName { get; set; }
        public int MedicineID { get; set; }
        public string MedicineName { get; set; }
        public System.DateTime ProjectedRestockDate { get; set; }
        public System.DateTime NextReminderDate { get; set; }
    
        public virtual MedicineTable MedicineTable { get; set; }
        public virtual PetTable PetTable { get; set; }
        public virtual PrescriptionTable PrescriptionTable { get; set; }
    }
}
